POST http://localhost:5197
Content-Type: application/json

{
  "query": "what is the capital city of France?"
}

###

POST http://localhost:5197
Content-Type: application/json

{
  "query": "which medical center is closest to my location (Sammamish, WA)?"
}

###

POST http://localhost:5197
Content-Type: application/json

{
  "query": "I live in Istanbul Turkey, and I want to uplift my nose. Where should I go?"
}


###
